services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false
    autoconfigure: false

  App\User\Controller\ManagerController:
    public: true
    arguments:
      - '@app.hasher.user_password'
      - '@app.repository.manager'
    calls:
      - method: setContainer
        arguments: [ '@Psr\Container\ContainerInterface' ]
    tags: [ 'container.service_subscriber', 'controller.service_arguments' ]

  App\User\Controller\CustomerController:
    public: true
    arguments:
      - '@app.hasher.user_password'
      - '@app.repository.manager'
      - '@app.repository.customer'
    calls:
      - method: setContainer
        arguments: [ '@Psr\Container\ContainerInterface' ]
    tags: [ 'container.service_subscriber', 'controller.service_arguments' ]

  App\MultimediaResource\Controller\MultimediaResourceController:
    public: true
    arguments:
      - '@app.repository.multimedia_resource'
      - '@app.manager.multimedia_resource'
    calls:
      - method: setContainer
        arguments: [ '@Psr\Container\ContainerInterface' ]
    tags: [ 'container.service_subscriber', 'controller.service_arguments' ]