services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false
    autoconfigure: false

  app.repository.manager:
    class: App\User\Repository\ManagerRepository
    arguments:
      - '@Doctrine\Persistence\ManagerRegistry'

  app.repository.customer:
    class: App\User\Repository\CustomerRepository
    arguments:
      - '@Doctrine\Persistence\ManagerRegistry'

  app.repository.multimedia_resource:
    class: App\MultimediaResource\Repository\MultimediaResourceRepository
    arguments:
      - '@Doctrine\Persistence\ManagerRegistry'