services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false
    autoconfigure: false

  app.voter.user:
    class: App\User\Voter\UserVoter
    tags:
      - { name: 'security.voter' }

  app.voter.multimedia_resource:
    class: App\MultimediaResource\Voter\MultimediaResourceVoter
    tags:
      - { name: 'security.voter' }